version: '2'
services:
  datajoint:
    build:
      context: .
      dockerfile: DevDockerfile
    environment:
      - DJ_HOST=db
      - DJ_USER=root
      - DJ_PASS=simple
      - DJ_TEST_HOST=db
      - DJ_TEST_USER=root
      - DJ_TEST_PASSWORD=simple
    volumes:
      - .:/src
    links:
      - db
    ports:
      - "8888:8888"
  db:
    image: mysql:5.7
    environment:
      - MYSQL_ROOT_PASSWORD=simple


